# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: Human-Centred Computing Research Group, Bangor University
tagline: ""
description: Human-Centred Computing research group,<br/> School of Computer Science and Engineering, <br/> College of Environmental Sciences and Engineering, Bangor University, </br>, Dean Street, Bangor, Gwynedd, UK, LL57 1UT<span>
url: https://hccbu.github.io/

destination: ./docs

author:
  name:
  url:

paginate: 15
paginate_path: "page:num"

# Custom vars
update: November 2025

github:
  repo:

collections:
  themes:
  faculty:
  ras:
  phd:
  former:
  labs:
  downloads:
  gallery:
  projects:
  seminars:
  projects:
      output: true
  seminarsarchive:
      output: true

twitter_username: "@hcc_bangor"

# BibTex Citation plugin
scholar:
  style: assets/ieee.csl
  locale: en
  #use_raw_bibtex_entry: true

  sort_by: year, month
  order: descending
  bibliography_list_tag: div
  bibliography_item_tag: p
  bibtex_skip_fields:
    [
      "note",
      "code",
      "info",
      "preview",
      "status",
      "abstract",
      "video",
      "month_numeric",
      "vmpreview",
      "ytpreview",
      "teaser",
      "ack",
      "url",
      "github",
      "tags",
      "dposter",
      "about",
      "cover",
      "nopaper",
      "preprint"
    ]

  source: ./_bibliography
  bibliography: "**/*.bib{,tex}"
  repository: files
  bibliography_template: bibliography


  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: <span hidden></span>

  query: "@*[status!=review]"

# Do not copy these file to the output directory
exclude: ["Icon", node_modules]

exclude:
  - .jekyll-cache

# Plugins
# plugins_dir: _plugins
#plugins:
#- jekyll-paginate
#- jekyll_figure
#- jekyll-sitemap
#- jekyll-minifier
#- jekyll-paginate
#- jekyll-scholar
#- jekyll-figure

jekyll-minifier:
  exclude: "atom.xml, robots.txt, CNAME, .htaccess" # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  preserve_php: true # Default: false
  remove_spaces_inside_tags: false # Default: true
  remove_multi_spaces: false # Default: true
  remove_comments: false # Default: true
  remove_intertag_spaces: false # Default: false
  remove_quotes: false # Default: false
  compress_css: true # Default: true
  compress_javascript: true # Default: true
  simple_doctype: false # Default: false
  remove_script_attributes: false # Default: false
  remove_style_attributes: false # Default: false
  remove_link_attributes: false # Default: false
  remove_form_attributes: false # Default: false
  remove_input_attributes: false # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false # Default: false
  remove_https_protocol: false # Default: false
  preserve_line_breaks: false # Default: false
  simple_boolean_attributes: false # Default: false
  compress_js_templates: false # Default: false

figures:
  dir: /assets/figures
  enumerate: true

include: [.htaccess, robots.txt]
